version: '3'

services:

  # DB

  mongo:
    build:
      context: ./mongo
    expose:
      - 27017
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/data:/data/db

  # SERVER

  server_dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./server:/app
