version: '3'

services:
  mongo:
    build:
      context: ./mongo
    expose:
      - 27017
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/data:/data/db

  server:
    build:
      context: ./
    command: dev
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
    ports:
      - 3000:3000
    volumes:
      - /server/node_modules
      - /frontend/node_modules
      - ./server:/server
      - ./frontend:/frontend
